---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-azresourcegraph
spec:
  package: xpkg.upbound.io/upboundcare/function-azresourcegraph:v0.0.0-20241211180855-5fbd8d144852
