---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-azresourcegraph
spec:
  package: xpkg.upbound.io/upboundcare/function-azresourcegraph:v0.2.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-environment-configs
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-environment-configs:v0.2.0
